[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
node-version = "18"

[service.frontend]
buildCommand = "cd client && npm install && npm run build"
startCommand = "cd client && npx serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 