[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
node-version = "18"

[service.backend]
directory = "server"
name = "backend"

[service.frontend]
directory = "client"
name = "frontend" 