[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

[nixpacks]
node-version = "18"

[service.backend]
directory = "server"
name = "backend"

[service.frontend]
directory = "client"
name = "frontend" 