[build]
builder = "nixpacks"
buildCommand = "cd .. && npm install && npm run build"

[deploy]
startCommand = "cd .. && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
node-version = "18" 